# -*- coding: utf-8 -*-
"""ssh_triage_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vv5Q91qnVTnpjpXqoUe_aVU_iKWiTIY9
"""

events = []
ip_list = []
from collections import Counter
with open("auth.log") as file:
    for line in file:
        if "Failed password" in line:
            ip = line.split()[10]
            user = line.split()[8]
            ip_list.append(ip)
            events.append((ip, user))
counts_ip = Counter(ip_list)
print(f"Failed attempts from most common IPs in descending order {counts_ip.most_common()}")

flagged_ips = []
for ip, count in counts_ip.items():
    if count >= 10:
        flagged_ips.append(ip)
for ip in flagged_ips:
    print(f"⚠️ ALERT: {ip} made {counts_ip[ip]} failed login attempts")

breached_events = []
breached_ip = []
with open("auth.log") as file:
    for line in file:
        if "Accepted password" in line:
          breach_ip = line.split()[10]
          if breach_ip in flagged_ips:
            breach_user = line.split()[8]
            breached_ip.append(breach_ip)
            breached_events.append((breach_ip, breach_user))
for ip, user in breached_events:
  print(f"🚨 CRITICAL: {ip} achieved a successful login as '{user}' after brute-force attempts")
